In [1]:
import pandas as pd
import json
import nltk
from nltk.tokenize import word_tokenize
import string
# Load the CSV file
file_path = 'cleaned_data.csv'
data = pd.read_csv(file_path)

data

C:\Users\haill\AppData\Local\Temp\ipykernel_16396\393795807.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

,Unnamed: 0,question,answer,question_as_int,answer_as_int,question_len,answer_len
0,1,Well I thought wed start with pronunciation if...,Not the hacking and gagging and spitting part ...,"[54, 67, 74, 74, 12, 1, 40, 1, 82, 70, 77, 83,...","[45, 77, 82, 1, 82, 70, 67, 1, 70, 63, 65, 73,...",71,55
1,2,Not the hacking and gagging and spitting part ...,Okay then how bout we try out some French cuis...,"[45, 77, 82, 1, 82, 70, 67, 1, 70, 63, 65, 73,...","[46, 73, 63, 87, 14, 14, 14, 1, 82, 70, 67, 76...",55,73
2,3,Youre asking me out Thats so cute Whats your ...,Forget it,"[56, 77, 83, 8, 80, 67, 1, 63, 81, 73, 71, 76,...","[37, 77, 80, 69, 67, 82, 1, 71, 82, 14]",62,10
3,4,No no its my fault we didnt have a proper int...,Cameron,"[45, 77, 12, 1, 76, 77, 12, 1, 71, 82, 8, 81, ...","[34, 63, 75, 67, 80, 77, 76, 14]",65,8
4,9,Gosh if only we could find Kat a boyfriend,Let me see what I can do,"[38, 77, 81, 70, 12, 1, 71, 68, 1, 77, 76, 74,...","[43, 67, 82, 1, 75, 67, 1, 81, 67, 67, 1, 85, ...",46,25
...,...,...,...,...,...,...,...
139404,221608,Well that one The one who keeps looking at me,ft could be you flatter yourself CoghilL Its t...,"[54, 67, 74, 74, 1, 82, 70, 63, 82, 1, 77, 76,...","[68, 82, 1, 65, 77, 83, 74, 66, 1, 64, 67, 1, ...",47,59
139405,221609,Choose your targets men Thats right Watch thos...,Keep steady Youre the best shots of the Twenty...,"[34, 70, 77, 77, 81, 67, 1, 87, 77, 83, 80, 1,...","[42, 67, 67, 78, 1, 81, 82, 67, 63, 66, 87, 14...",61,85
139406,221610,Colonel Durnford William Vereker I hear you ve...,Good ones yes Mr Vereker Gentlemen who can rid...,"[34, 77, 74, 77, 76, 67, 74, 1, 35, 83, 80, 76...","[38, 77, 77, 66, 1, 77, 76, 67, 81, 12, 1, 87,...",74,60
139407,221611,Your orders Mr Vereker ?,Im to take the Sikali with the main column to ...,"[56, 77, 83, 80, 1, 77, 80, 66, 67, 80, 81, 12...","[40, 8, 75, 1, 82, 77, 1, 82, 63, 73, 67, 1, 8...",24,56
139408,221612,Im to take the Sikali with the main column to ...,Lord Chelmsford seems to want me to stay back ...,"[40, 8, 75, 1, 82, 77, 1, 82, 63, 73, 67, 1, 8...","[43, 77, 80, 66, 1, 34, 70, 67, 74, 75, 81, 68...",56,62

In [2]:
correct_formatted_pairs = []

# Iterate over each row in the DataFrame to correctly format the question and answer pairs
for index, row in data.iterrows():
    corrected_formatted_question = f"</start> {row['question']} </s> {row['answer']} </end> "
    # Append the correctly formatted pair
    correct_formatted_pairs.append(corrected_formatted_question)

# Combine all pairs into a single graph representation with the corrected format
correct_graph_representation = "".join(correct_formatted_pairs)

# Encode the corrected graph representation to ASCII code
# correct_ascii_encoded_graph = [ord(char) for char in correct_graph_representation]

# Create a new JSON file with the corrected ASCII encoded graph
correct_encoded_graph_path = 'clean_data/gathered_graph.json'
with open(correct_encoded_graph_path, 'w') as file:
    json.dump(correct_graph_representation, file)

correct_encoded_graph_path

'clean_data/gathered_graph.json'